-- Módulo de proyectos web: completamente separado de reparaciones.
create table if not exists public.web_proyectos (
  id bigint generated by default as identity primary key,
  codigo text unique,
  cliente_nombre text not null,
  cliente_empresa text,
  cliente_telefono text,
  cliente_email text,
  plan text not null default 'A medida',
  estado text not null default 'consulta'
    check (estado in ('consulta', 'presupuesto', 'sena_pendiente', 'diseno', 'desarrollo', 'revision', 'publicado', 'mantenimiento', 'cancelado')),
  importe_usd numeric(12,2),
  importe_ars numeric(14,2),
  sena_usd numeric(12,2),
  saldo_usd numeric(12,2),
  dominio text,
  url_publica text,
  fecha_inicio date,
  fecha_entrega date,
  proxima_renovacion date,
  dominio_estado text not null default 'pendiente'
    check (dominio_estado in ('pendiente', 'ok', 'error')),
  dominio_detalle text,
  hosting_estado text not null default 'pendiente'
    check (hosting_estado in ('pendiente', 'ok', 'error')),
  hosting_detalle text,
  sitio_estado text not null default 'pendiente'
    check (sitio_estado in ('pendiente', 'ok', 'error')),
  sitio_detalle text,
  notas text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists web_proyectos_estado_idx on public.web_proyectos (estado);
create index if not exists web_proyectos_created_at_idx on public.web_proyectos (created_at desc);

create or replace function public.set_web_proyecto_codigo()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.codigo is null or btrim(new.codigo) = '' then
    new.codigo := 'WEB-' || lpad(new.id::text, 4, '0');
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_web_proyecto_codigo on public.web_proyectos;
create trigger set_web_proyecto_codigo
before insert or update on public.web_proyectos
for each row execute function public.set_web_proyecto_codigo();

-- The existing admin uses the public Data API with its own browser login.
-- Keep this module compatible with that legacy access model; migrate the whole
-- admin to Supabase Auth before introducing private customer data or public forms.
alter table public.web_proyectos enable row level security;
grant select, insert, update, delete on public.web_proyectos to anon;
grant usage, select on sequence public.web_proyectos_id_seq to anon;
create policy "legacy admin can manage web projects"
on public.web_proyectos
for all
to anon
using (true)
with check (true);
